import { Product } from "@/types/product-type";

export const EVENT_CATEGORIES = [
  "All Events",
  "Music",
  "Sports",
  "Arts & Theater",
  "Business & Professional",
  "Food & Drink",
  "Health & Wellness",
  "Technology",
] as const;

export type EventCategory = (typeof EVENT_CATEGORIES)[number];

export const DUMMY_EVENTS: Product[] = [
  {
    id: "evt-001",
    code: "JAZZ-NIGHT-2026",
    name: "Summer Jazz Festival",
    description:
      "Experience an unforgettable evening of smooth jazz featuring renowned artists from around the world. Enjoy craft cocktails and gourmet food under the stars.",
    category: "Music",
    startDate: "2026-06-15",
    startTime: "19:00",
    endDate: "2026-06-15",
    endTime: "23:00",
    address: "Central Park Amphitheater, New York, NY",
    imageUrl: "https://picsum.photos/seed/jazz/800/400",
    productItems: [
      {
        id: "item-001-1",
        name: "General Admission",
        description: "Standing room access to the main stage area",
        variants: "Standard",
        unitPrice: 45.0,
        isFree: false,
      },
      {
        id: "item-001-2",
        name: "VIP Package",
        description: "Premium seating, backstage access, and meet & greet",
        variants: "Premium",
        unitPrice: 125.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-002",
    code: "MARATHON-2026",
    name: "City Marathon Championship",
    description:
      "Join thousands of runners in this annual marathon through the city's most scenic routes. All skill levels welcome, from beginners to elite athletes.",
    category: "Sports",
    startDate: "2026-04-20",
    startTime: "07:00",
    endDate: "2026-04-20",
    endTime: "14:00",
    address: "Downtown Start Line, Boston, MA",
    imageUrl: "https://picsum.photos/seed/marathon/800/400",
    productItems: [
      {
        id: "item-002-1",
        name: "Full Marathon (42.2km)",
        description: "Complete marathon distance",
        variants: "Standard",
        unitPrice: 85.0,
        isFree: false,
      },
      {
        id: "item-002-2",
        name: "Half Marathon (21.1km)",
        description: "Half marathon distance",
        variants: "Standard",
        unitPrice: 55.0,
        isFree: false,
      },
      {
        id: "item-002-3",
        name: "5K Fun Run",
        description: "Family-friendly 5K run",
        variants: "Standard",
        unitPrice: 25.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-003",
    code: "HAMLET-REVIVAL",
    name: "Hamlet: A Modern Revival",
    description:
      "Shakespeare's timeless tragedy reimagined for the modern age. Award-winning director brings fresh perspective to this classic tale of revenge and madness.",
    category: "Arts & Theater",
    startDate: "2026-05-10",
    startTime: "20:00",
    endDate: "2026-05-10",
    endTime: "22:30",
    address: "Broadway Theater District, New York, NY",
    imageUrl: "https://picsum.photos/seed/hamlet/800/400",
    productItems: [
      {
        id: "item-003-1",
        name: "Orchestra Seating",
        description: "Best seats in the house",
        variants: "Premium",
        unitPrice: 95.0,
        isFree: false,
      },
      {
        id: "item-003-2",
        name: "Mezzanine",
        description: "Elevated view with great sightlines",
        variants: "Standard",
        unitPrice: 65.0,
        isFree: false,
      },
      {
        id: "item-003-3",
        name: "Balcony",
        description: "Affordable seating option",
        variants: "Budget",
        unitPrice: 35.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-004",
    code: "TECH-SUMMIT-2026",
    name: "Future Tech Summit 2026",
    description:
      "Discover the latest innovations in AI, blockchain, and quantum computing. Network with industry leaders and attend hands-on workshops.",
    category: "Technology",
    startDate: "2026-07-08",
    startTime: "09:00",
    endDate: "2026-07-10",
    endTime: "18:00",
    address: "Convention Center, San Francisco, CA",
    imageUrl: "https://picsum.photos/seed/techsummit/800/400",
    productItems: [
      {
        id: "item-004-1",
        name: "3-Day Conference Pass",
        description: "Full access to all sessions and workshops",
        variants: "Standard",
        unitPrice: 450.0,
        isFree: false,
      },
      {
        id: "item-004-2",
        name: "Single Day Pass",
        description: "Access for one day of your choice",
        variants: "Standard",
        unitPrice: 175.0,
        isFree: false,
      },
      {
        id: "item-004-3",
        name: "Student Pass",
        description: "Discounted rate for students with valid ID",
        variants: "Student",
        unitPrice: 99.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-005",
    code: "FOOD-FEST-2026",
    name: "International Food & Wine Festival",
    description:
      "Taste your way around the world with dishes from 50+ countries. Wine tastings, cooking demos, and live entertainment throughout the day.",
    category: "Food & Drink",
    startDate: "2026-08-22",
    startTime: "12:00",
    endDate: "2026-08-22",
    endTime: "21:00",
    address: "Waterfront Park, Seattle, WA",
    imageUrl: "https://picsum.photos/seed/foodfest/800/400",
    productItems: [
      {
        id: "item-005-1",
        name: "General Admission",
        description: "Entry to festival grounds",
        variants: "Standard",
        unitPrice: 0,
        isFree: true,
      },
      {
        id: "item-005-2",
        name: "Tasting Pass (20 tickets)",
        description: "Sample tickets for food and drinks",
        variants: "Standard",
        unitPrice: 40.0,
        isFree: false,
      },
      {
        id: "item-005-3",
        name: "VIP Tasting Pass (50 tickets)",
        description: "Premium samples and lounge access",
        variants: "Premium",
        unitPrice: 95.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-006",
    code: "WELLNESS-RETREAT",
    name: "Mindfulness & Wellness Retreat",
    description:
      "A transformative weekend of yoga, meditation, and holistic health workshops. Reconnect with yourself in a serene natural setting.",
    category: "Health & Wellness",
    startDate: "2026-09-12",
    startTime: "08:00",
    endDate: "2026-09-14",
    endTime: "17:00",
    address: "Mountain Retreat Center, Sedona, AZ",
    imageUrl: "https://picsum.photos/seed/wellness/800/400",
    productItems: [
      {
        id: "item-006-1",
        name: "Weekend Package",
        description: "All workshops, meals, and accommodation",
        variants: "All-Inclusive",
        unitPrice: 450.0,
        isFree: false,
      },
      {
        id: "item-006-2",
        name: "Day Pass (Saturday)",
        description: "Saturday workshops and lunch",
        variants: "Standard",
        unitPrice: 125.0,
        isFree: false,
      },
      {
        id: "item-006-3",
        name: "Day Pass (Sunday)",
        description: "Sunday workshops and lunch",
        variants: "Standard",
        unitPrice: 125.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-007",
    code: "STARTUP-PITCH",
    name: "Startup Pitch Competition",
    description:
      "Watch innovative startups compete for $100K in funding. Network with investors, entrepreneurs, and industry experts.",
    category: "Business & Professional",
    startDate: "2026-10-05",
    startTime: "13:00",
    endDate: "2026-10-05",
    endTime: "19:00",
    address: "Innovation Hub, Austin, TX",
    imageUrl: "https://picsum.photos/seed/startup/800/400",
    productItems: [
      {
        id: "item-007-1",
        name: "Attendee Ticket",
        description: "Watch the competition and network",
        variants: "Standard",
        unitPrice: 0,
        isFree: true,
      },
      {
        id: "item-007-2",
        name: "Investor Pass",
        description: "Networking lounge and private meetings",
        variants: "Premium",
        unitPrice: 250.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-008",
    code: "ROCK-CONCERT-2026",
    name: "Electric Thunder Rock Concert",
    description:
      "The hottest rock bands come together for one epic night. Featuring headliners The Voltage and special guests.",
    category: "Music",
    startDate: "2026-11-18",
    startTime: "18:30",
    endDate: "2026-11-18",
    endTime: "23:30",
    address: "Arena Stadium, Los Angeles, CA",
    imageUrl: "https://picsum.photos/seed/rockconcert/800/400",
    productItems: [
      {
        id: "item-008-1",
        name: "Floor Standing",
        description: "Standing room near the stage",
        variants: "Standard",
        unitPrice: 75.0,
        isFree: false,
      },
      {
        id: "item-008-2",
        name: "Reserved Seating",
        description: "Comfortable seats with great views",
        variants: "Standard",
        unitPrice: 55.0,
        isFree: false,
      },
      {
        id: "item-008-3",
        name: "Upper Level",
        description: "Affordable seating option",
        variants: "Budget",
        unitPrice: 35.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-009",
    code: "BALLET-SWAN-2026",
    name: "Swan Lake: Royal Ballet",
    description:
      "The world-renowned Royal Ballet presents Tchaikovsky's Swan Lake in a breathtaking production featuring stunning sets, costumes, and world-class dancers.",
    category: "Arts & Theater",
    startDate: "2026-03-28",
    startTime: "19:30",
    endDate: "2026-03-28",
    endTime: "22:00",
    address: "Opera House, Chicago, IL",
    imageUrl: "https://picsum.photos/seed/ballet/800/400",
    productItems: [
      {
        id: "item-009-1",
        name: "Premium Stalls",
        description: "Front rows with the best view of the stage",
        variants: "Premium",
        unitPrice: 110.0,
        isFree: false,
      },
      {
        id: "item-009-2",
        name: "Rear Stalls",
        description: "Great sightlines from the back of the stalls",
        variants: "Standard",
        unitPrice: 75.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-010",
    code: "TRIATHLON-2026",
    name: "Iron Coast Triathlon",
    description:
      "Take on the ultimate endurance challenge: 1.5km swim, 40km cycle, 10km run along the stunning Pacific coast. Open to all fitness levels.",
    category: "Sports",
    startDate: "2026-05-30",
    startTime: "06:30",
    endDate: "2026-05-30",
    endTime: "15:00",
    address: "Santa Monica Beach, Los Angeles, CA",
    imageUrl: "https://picsum.photos/seed/triathlon/800/400",
    productItems: [
      {
        id: "item-010-1",
        name: "Standard Entry",
        description: "Individual entry to the full triathlon",
        variants: "Standard",
        unitPrice: 120.0,
        isFree: false,
      },
      {
        id: "item-010-2",
        name: "Relay Team Entry",
        description: "Team of 3 each doing one leg",
        variants: "Team",
        unitPrice: 90.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-011",
    code: "AI-WORKSHOP-2026",
    name: "AI & Machine Learning Workshop",
    description:
      "A hands-on full-day workshop covering practical machine learning with Python, LLM fine-tuning, and deploying AI applications to production.",
    category: "Technology",
    startDate: "2026-06-27",
    startTime: "09:00",
    endDate: "2026-06-27",
    endTime: "17:00",
    address: "Tech Campus, Seattle, WA",
    imageUrl: "https://picsum.photos/seed/aiworkshop/800/400",
    productItems: [
      {
        id: "item-011-1",
        name: "Workshop Seat",
        description: "Full-day workshop with materials and lunch included",
        variants: "Standard",
        unitPrice: 199.0,
        isFree: false,
      },
      {
        id: "item-011-2",
        name: "Early Bird Seat",
        description: "Discounted seat for bookings made 60+ days in advance",
        variants: "Early Bird",
        unitPrice: 149.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-012",
    code: "BEER-FEST-2026",
    name: "Craft Beer & BBQ Festival",
    description:
      "Sample over 150 craft beers from local and international breweries, paired with slow-cooked BBQ from award-winning pitmasters.",
    category: "Food & Drink",
    startDate: "2026-07-25",
    startTime: "13:00",
    endDate: "2026-07-25",
    endTime: "22:00",
    address: "Riverside Park, Denver, CO",
    imageUrl: "https://picsum.photos/seed/beerfest/800/400",
    productItems: [
      {
        id: "item-012-1",
        name: "Entry + 10 Tasting Tokens",
        description: "Gate entry with 10 beer tasting tokens",
        variants: "Standard",
        unitPrice: 35.0,
        isFree: false,
      },
      {
        id: "item-012-2",
        name: "VIP Entry + 25 Tokens + BBQ Plate",
        description: "VIP entry, 25 tokens, and a full BBQ plate",
        variants: "VIP",
        unitPrice: 75.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-013",
    code: "LEADERSHIP-CONF-2026",
    name: "Women in Leadership Conference",
    description:
      "Two days of inspiring keynotes, panel discussions, and networking sessions empowering women to advance in their careers and industries.",
    category: "Business & Professional",
    startDate: "2026-08-13",
    startTime: "08:30",
    endDate: "2026-08-14",
    endTime: "17:30",
    address: "Grand Hyatt, Washington, DC",
    imageUrl: "https://picsum.photos/seed/leadership/800/400",
    productItems: [
      {
        id: "item-013-1",
        name: "2-Day Pass",
        description: "Full conference access for both days",
        variants: "Standard",
        unitPrice: 299.0,
        isFree: false,
      },
      {
        id: "item-013-2",
        name: "Single Day Pass",
        description: "Access for one day of your choice",
        variants: "Standard",
        unitPrice: 175.0,
        isFree: false,
      },
      {
        id: "item-013-3",
        name: "Virtual Attendance",
        description: "Livestream access to all keynotes and panels",
        variants: "Virtual",
        unitPrice: 49.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-014",
    code: "YOGA-FEST-2026",
    name: "Sunrise Yoga & Sound Bath Festival",
    description:
      "Greet the morning with guided yoga on the beach followed by a 90-minute crystal bowl sound bath. Suitable for all levels.",
    category: "Health & Wellness",
    startDate: "2026-09-27",
    startTime: "06:00",
    endDate: "2026-09-27",
    endTime: "10:00",
    address: "Venice Beach, Los Angeles, CA",
    imageUrl: "https://picsum.photos/seed/yogafest/800/400",
    productItems: [
      {
        id: "item-014-1",
        name: "Yoga + Sound Bath",
        description: "Full morning experience including both sessions",
        variants: "Standard",
        unitPrice: 40.0,
        isFree: false,
      },
      {
        id: "item-014-2",
        name: "Sound Bath Only",
        description: "90-minute crystal bowl sound bath session",
        variants: "Standard",
        unitPrice: 20.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-015",
    code: "INDIE-MUSIC-2026",
    name: "Indie Horizons Music Festival",
    description:
      "Three stages, 30 indie artists, two unforgettable days. Discover your next favourite band in an intimate outdoor festival setting.",
    category: "Music",
    startDate: "2026-10-17",
    startTime: "12:00",
    endDate: "2026-10-18",
    endTime: "23:00",
    address: "Meadow Grounds, Portland, OR",
    imageUrl: "https://picsum.photos/seed/indiefest/800/400",
    productItems: [
      {
        id: "item-015-1",
        name: "Weekend Pass",
        description: "Both days, all stages",
        variants: "Standard",
        unitPrice: 90.0,
        isFree: false,
      },
      {
        id: "item-015-2",
        name: "Saturday Day Pass",
        description: "Saturday only access",
        variants: "Standard",
        unitPrice: 55.0,
        isFree: false,
      },
      {
        id: "item-015-3",
        name: "Sunday Day Pass",
        description: "Sunday only access",
        variants: "Standard",
        unitPrice: 55.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-016",
    code: "HACKATHON-2026",
    name: "48-Hour Innovation Hackathon",
    description:
      "Form a team, pick a problem, build a solution. Compete for $50K in prizes while collaborating with brilliant minds from across the tech industry.",
    category: "Technology",
    startDate: "2026-11-06",
    startTime: "18:00",
    endDate: "2026-11-08",
    endTime: "18:00",
    address: "Innovation Hub, Austin, TX",
    imageUrl: "https://picsum.photos/seed/hackathon/800/400",
    productItems: [
      {
        id: "item-016-1",
        name: "Individual Registration",
        description: "Solo participant entry — we'll help you find a team",
        variants: "Standard",
        unitPrice: 0,
        isFree: true,
      },
      {
        id: "item-016-2",
        name: "Team Registration (up to 4)",
        description: "Register your team of up to 4 people",
        variants: "Team",
        unitPrice: 0,
        isFree: true,
      },
    ],
  },
  {
    id: "evt-017",
    code: "OPERA-2026",
    name: "La Traviata — Grand Opera Night",
    description:
      "Verdi's masterpiece performed by an internationally acclaimed cast. An opulent evening of passion, tragedy, and extraordinary vocal talent.",
    category: "Arts & Theater",
    startDate: "2026-04-03",
    startTime: "19:00",
    endDate: "2026-04-03",
    endTime: "22:30",
    address: "Metropolitan Opera House, New York, NY",
    imageUrl: "https://picsum.photos/seed/opera2026/800/400",
    productItems: [
      {
        id: "item-017-1",
        name: "Orchestra",
        description: "Front orchestra seating",
        variants: "Premium",
        unitPrice: 140.0,
        isFree: false,
      },
      {
        id: "item-017-2",
        name: "Dress Circle",
        description: "Elevated circle seating",
        variants: "Standard",
        unitPrice: 90.0,
        isFree: false,
      },
      {
        id: "item-017-3",
        name: "Gallery",
        description: "Upper gallery seats",
        variants: "Budget",
        unitPrice: 35.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-018",
    code: "SURF-COMP-2026",
    name: "Pacific Surf Open Championship",
    description:
      "Watch world-class surfers battle massive Pacific swells in this thrilling open competition. Spectator access is free on the beach.",
    category: "Sports",
    startDate: "2026-05-02",
    startTime: "08:00",
    endDate: "2026-05-03",
    endTime: "17:00",
    address: "Huntington Beach Pier, CA",
    imageUrl: "https://picsum.photos/seed/surfopen/800/400",
    productItems: [
      {
        id: "item-018-1",
        name: "Beach Spectator Pass",
        description: "Free beach access for both days",
        variants: "Standard",
        unitPrice: 0,
        isFree: true,
      },
      {
        id: "item-018-2",
        name: "VIP Grandstand Seat",
        description: "Reserved grandstand seating with catering",
        variants: "VIP",
        unitPrice: 60.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-019",
    code: "CYBER-SEC-2026",
    name: "CyberSec Pro Conference",
    description:
      "The premier cybersecurity conference covering ethical hacking, zero-trust architecture, and the latest threat intelligence. Includes CTF competition.",
    category: "Technology",
    startDate: "2026-06-04",
    startTime: "09:00",
    endDate: "2026-06-05",
    endTime: "18:00",
    address: "Moscone Center, San Francisco, CA",
    imageUrl: "https://picsum.photos/seed/cybersec/800/400",
    productItems: [
      {
        id: "item-019-1",
        name: "2-Day Full Pass",
        description: "All sessions, workshops, and CTF entry",
        variants: "Standard",
        unitPrice: 350.0,
        isFree: false,
      },
      {
        id: "item-019-2",
        name: "Virtual Pass",
        description: "Live stream access to all keynotes",
        variants: "Virtual",
        unitPrice: 79.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-020",
    code: "CHOCOLATE-FEST-2026",
    name: "Artisan Chocolate & Dessert Festival",
    description:
      "Indulge in creations from 80+ chocolatiers and pastry chefs. Live demonstrations, pairing workshops, and a golden ticket competition.",
    category: "Food & Drink",
    startDate: "2026-07-11",
    startTime: "11:00",
    endDate: "2026-07-12",
    endTime: "20:00",
    address: "Ferry Building, San Francisco, CA",
    imageUrl: "https://picsum.photos/seed/chocofest/800/400",
    productItems: [
      {
        id: "item-020-1",
        name: "Weekend Entry",
        description: "Entry for both days",
        variants: "Standard",
        unitPrice: 20.0,
        isFree: false,
      },
      {
        id: "item-020-2",
        name: "Tasting Workshop Ticket",
        description: "Entry + guided chocolate tasting workshop",
        variants: "Premium",
        unitPrice: 65.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-021",
    code: "ENTREPRENEUR-BOOT-2026",
    name: "Entrepreneur Bootcamp Intensive",
    description:
      "A three-day immersive bootcamp for early-stage founders. Covers product-market fit, fundraising, go-to-market strategy, and pitch practice.",
    category: "Business & Professional",
    startDate: "2026-08-03",
    startTime: "08:00",
    endDate: "2026-08-05",
    endTime: "17:00",
    address: "Startup Campus, Miami, FL",
    imageUrl: "https://picsum.photos/seed/entbootcamp/800/400",
    productItems: [
      {
        id: "item-021-1",
        name: "Full Bootcamp",
        description: "3-day in-person program with meals",
        variants: "Standard",
        unitPrice: 599.0,
        isFree: false,
      },
      {
        id: "item-021-2",
        name: "Online Cohort",
        description: "Remote participation via live stream",
        variants: "Virtual",
        unitPrice: 199.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-022",
    code: "PILATES-SUMMIT-2026",
    name: "Pilates & Functional Fitness Summit",
    description:
      "Two days of Pilates workshops, movement science talks, and functional fitness challenges led by top coaches from around the world.",
    category: "Health & Wellness",
    startDate: "2026-09-05",
    startTime: "09:00",
    endDate: "2026-09-06",
    endTime: "17:00",
    address: "Wellness Arena, Dallas, TX",
    imageUrl: "https://picsum.photos/seed/pilates/800/400",
    productItems: [
      {
        id: "item-022-1",
        name: "2-Day Pass",
        description: "All workshops and sessions",
        variants: "Standard",
        unitPrice: 175.0,
        isFree: false,
      },
      {
        id: "item-022-2",
        name: "1-Day Pass",
        description: "Single day access",
        variants: "Standard",
        unitPrice: 95.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-023",
    code: "CLASSICAL-PROM-2026",
    name: "Last Night of the Proms",
    description:
      "A spectacular celebration of classical music featuring a full symphony orchestra, choir, and fireworks finale. A beloved British tradition brought to America.",
    category: "Music",
    startDate: "2026-09-12",
    startTime: "19:00",
    endDate: "2026-09-12",
    endTime: "22:00",
    address: "Hollywood Bowl, Los Angeles, CA",
    imageUrl: "https://picsum.photos/seed/proms/800/400",
    productItems: [
      {
        id: "item-023-1",
        name: "Reserved Terrace",
        description: "Comfortable reserved terrace seating",
        variants: "Premium",
        unitPrice: 85.0,
        isFree: false,
      },
      {
        id: "item-023-2",
        name: "Garden Box",
        description: "Shared garden box for groups of 4",
        variants: "Standard",
        unitPrice: 55.0,
        isFree: false,
      },
      {
        id: "item-023-3",
        name: "Lawn Admission",
        description: "Bring your own blanket — open lawn area",
        variants: "Budget",
        unitPrice: 22.0,
        isFree: false,
      },
    ],
  },
  {
    id: "evt-024",
    code: "ROBOTICS-EXPO-2026",
    name: "Robotics & Automation Expo",
    description:
      "See the future of automation up close. Live robot demonstrations, drone racing, and panel discussions on the impact of AI-driven robotics across industries.",
    category: "Technology",
    startDate: "2026-10-22",
    startTime: "10:00",
    endDate: "2026-10-23",
    endTime: "18:00",
    address: "McCormick Place, Chicago, IL",
    imageUrl: "https://picsum.photos/seed/roboticsexpo/800/400",
    productItems: [
      {
        id: "item-024-1",
        name: "General Admission",
        description: "Full expo floor access for one day",
        variants: "Standard",
        unitPrice: 0,
        isFree: true,
      },
      {
        id: "item-024-2",
        name: "2-Day Pro Pass",
        description: "Both days + workshop sessions + networking dinner",
        variants: "Premium",
        unitPrice: 150.0,
        isFree: false,
      },
    ],
  },
];
