export const ORDER_ERRORS = {
  CREATE_ORDER_FAILED: "ORDER.CREATE_FAILED",
  CREATE_ORDER_WITH_PAYMENT_FAILED: "ORDER.CREATE_WITH_PAYMENT_FAILED",
  MARK_ORDER_AS_PAID_FAILED: "ORDER.MARK_AS_PAID_FAILED",
  VERIFY_ORDER_FAILED: "ORDER.VERIFY_FAILED",
};
